### ISSUE TITLE
使用【dit xvg_show_stack】报错【IndexError: list index out of range】

### ISSUE THREAD

**Issue by Lyueyang2020** [CharlesHahn/DuIvyTools#7]
首先非常感谢您的贡献，作为该工具的初次使用者，在使用【xvg_show_stack】绘制绘制堆积折线图时我遇到了以下问题：
命令为：dit xvg_show_stack -f dssp.xvg -c 2-8 -xs 0.001 -x "Time (ns)"
报错如下：
”Warning -> string column may detected, data_heads 2 < column_num 8
2023-12-07 17:20:34
Info -> parsing data from dssp1_557_.xvg successfully !
Traceback (most recent call last):
  File "/home/miniconda3/bin/dit", line 8, in <module>
    sys.exit(main())
  File "/home/miniconda3/lib/python3.8/site-packages/DuIvyTools/DuIvyTools/DIT.py", line 138, in main
    dit.run()
  File "/home/miniconda3/lib/python3.8/site-packages/DuIvyTools/DuIvyTools/DIT.py", line 134, in run
    cmd()
  File "/home/miniconda3/lib/python3.8/site-packages/DuIvyTools/DuIvyTools/Commands/xvgCommands.py", line 1135, in __call__
    legends.append(self.file.data_heads[column_indexs[i]])
IndexError: list index out of range”
非常感激您的回复，由于本人毫无编程基础，检索该问题的解决办法后也无法解决，（dssp.xvg见附件dssp.txt,*xvg文件格式限制上传）。祝您身体健康工作顺利！

[dssp.txt](https://github.com/CharlesHahn/DuIvyTools/files/13598202/dssp.txt)

**Comment by CharlesHahn** [comment]
Wrong file format in your dssp.txt, the head part of dssp_sc.xvg file generated by gmx do_dssp should not be deleted for using as input of DIT. 
你提供的文件当中很重要的数据列名称的部分被删掉了，这部分在xvg文件里面是有意义的。还搞不定的话[杜艾维]公众号联系我
